- package.json
- src/BaseElementTypes.ts
- src/components/shared/useBtRef.hooks.ts
- yarn.lock
- feat: allow to set expiration date from Card token
- [] Not Applicable
-
> feat: allow to set expiration date from Card token

- ios/AwesomeProject.xcodeproj/project.pbxproj
- ios/AwesomeProject.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- ios/Podfile.lock
- jest.config.js
- package.json
- setup.jest.js
- src/components/shared/useMask.ts
- src/modules/proxy.ts
- src/modules/sessions.ts
- src/modules/tokens.ts
- src/useBasisTheory.ts
- src/utils/logging.ts
- tests/utils/dataManipulationUtils.test.ts
- yarn.lock
- feat: adds datadog logging
-
> feat: adds datadog logging

- android/settings.gradle
- src/components/CardNumberElement.hooks.ts
- src/components/TextElement.hooks.ts
- src/components/shared/useTransform.ts
- src/components/shared/useUserEventHandlers.ts
> feat: adds transform

- package.json
- yarn.lock
> feat: bump ramda types

- package.json
- feat: add 'latest' tag to release
RN tags are not working correctly, latest still points to `beta.3` and master is on `beta.13`
-
> feat: add 'latest' tag to release

- tsconfig.json
- fix: remove `extends` from tsconfig
-
> fix: remove `extends` from tsconfig

- package.json
- yarn.lock
- fix: rebuild lockfile
Dry run works properly after installing semver as devDependency
-
> fix: rebuild lockfile and install semver as devDependency

- .releaserc.json
- package.json
- yarn.lock
> feat: update .releaserc

- demo/Collect.tsx
- src/modules/tokens.ts
- src/useBasisTheory.ts
- feat: surfaces update token
https://github.com/Basis-Theory/basis-theory-react-native/assets/13756889/26b01f06-515a-4a79-959b-bb8174f83ad5
-
> feat: surfaces update token

- src/useBasisTheory.ts
- fix: fix initialization w custom config object
-
> fix: fix initialization w custom config object

- demo/Collect.tsx
- demo/styles.ts
- src/modules/tokens.ts
- src/utils/dataManipulationUtils.ts
- src/utils/logging.ts
- tests/modules/tokens.test.ts
- tests/utils/dataManipulationUtils.test.ts
- feat: exposes token delete and tokenize
- fix: improves error handling for element initialization
- feat: update collect examples
-
> feat: exposes token delete and tokenize

- demo/Collect.tsx
- src/modules/tokens.ts
- src/utils/dataManipulationUtils.ts
- src/utils/shared.ts
- tests/utils/dataManipulationUtils.test.ts
- fix: improves handling of falsy values 
- fix: improves logging in tokens operations
https://github.com/Basis-Theory/basis-theory-react-native/assets/13756889/4a68d5dc-b7fa-4c34-9baa-8e9307a7d6f2
https://github.com/Basis-Theory/basis-theory-react-native/assets/13756889/5dc2d370-4111-42e5-9530-5583716fd450
- [] Not Applicable
-
> fix: improves handling of falsy values 

- package.json
- yarn.lock
> chore: upgrade dev deps

- package.json
- yarn.lock
- chore: upgrade dev dependencies
-
> chore: upgrade dev dependencies

- src/components/CardExpirationDateElement.hook.ts
- src/components/CardNumberElement.hook.ts
- src/components/CardVerificationCodeElement.hook.ts
- src/components/TextElement.hook.ts
- src/components/TextElement.tsx
- src/components/shared/useCleanStateOnUnmount.ts
- tests/components/CardNumberElement.test.tsx
- feat: adds support for secureTextEntry in text element
- fix: drops usage of UUID for element ID generation
- fix: cleans up orphaned state entries before unmounting
-
> feat: adds support for secureTextEntry in text element

- src/components/TextElement.tsx
- feat: adds new props to TextElement
- `keyboardType`
- `secureTextEntry`
- `textContentType`
-
> feat: adds new props to TextElement

- .gitignore
- package.json
- yarn.lock
- fixes: https://github.com/Basis-Theory/basis-theory-react-native/actions/runs/10272035558/job/28423344569
-
> fix: babel traverse error during build

- package.json
- yarn.lock
> fix: relax react version

- demo/Collect.tsx
- package.json
- src/components/CardExpirationDateElement.tsx
- src/components/CardNumberElement.tsx
- src/components/CardVerificationCodeElement.tsx
- yarn.lock
- feat: adds keyboard type to card* elements
-
> feat: adds keyboard type to card* elements

- .github/workflows/pull-request.yml
- .github/workflows/release.yml
- workflow updates for new secrets management
-
> chore: workflow updates for new secrets mgmt

- .github/workflows/security-scan.yml
- update security scan to use duckbot 
-
> chore: updates to security scan

- README.md
- demo/Collect.tsx
- package.json
- src/BaseElementTypes.ts
- src/components/CardVerificationCodeElement.hook.ts
- src/utils/validation.ts
- yarn.lock
- fix: add card metadata types to element event
- docs: update demo app to use dynamic cvc length
- feat: upgrade btjs
- feat: use dynamic cvc in cvc validator
https://github.com/user-attachments/assets/7902eb83-3274-4d7b-9895-2904e0816b5a
-
> fix: add types for card number element events
